export  const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_USER_RESET = "REGISTER_USER_RESET";

export  const REGISTER_AGENT_REQUEST = "REGISTER_AGENT_REQUEST";
export  const REGISTER_AGENT_SUCCESS = "REGISTER_AGENT_SUCCESS";
export  const REGISTER_AGENT_FAIL = "REGISTER_AGENT_FAIL";
export  const REGISTER_AGENT_RESET = "REGISTER_AGENT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REGISTER_COMPANY_REQUEST="REGISTER_COMPANY_REQUEST";
export const REGISTER_COMPANY_SUCCESS="REGISTER_COMPANY_SUCCESS";
export const REGISTER_COMPANY_FAIL="REGISTER_COMPANY_FAIL";
export const REGISTER_COMPANY_RESET="REGISTER_COMPANY_RESET";
export const REGISTER_BANK_REQUEST = "REGISTER_BANK_REQUEST";
export const REGISTER_BANK_SUCCESS = "REGISTER_BANK_SUCCESS";
export const REGISTER_BANK_FAIL = "REGISTER_BANK_FAIL";
export const REGISTER_BANK_RESET="REGISTER_BANK_RESET";

export const REGISTER_BRANCH_REQUEST = "REGISTER_BRANCH_REQUEST";
export const REGISTER_BRANCH_SUCCESS = "REGISTER_BRANCH_SUCCESS";
export const REGISTER_BRANCH_FAIL = "REGISTER_BRANCH_FAIL";
export const REGISTER_BRANCH_RESET="REGISTER_BRANCH_RESET";


export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER_RESET="LOGIN_USER_RESET";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const GET_USER_INFO_REQUEST = "GET_USER_INFO_REQUEST";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAIL = "GET_USER_INFO_FAIL";

export const GET_ADMIN_USER_INFO_REQUEST = "GET_ADMIN_USER_INFO_REQUEST";
export const GET_ADMIN_USER_INFO_SUCCESS = "GET_ADMIN_USER_INFO_SUCCESS";
export const GET_ADMIN_USER_INFO_FAIL = "GET_ADMIN_USER_INFO_FAIL";

export const GET_AGENT_INFO_REQUEST = "GET_AGENT_INFO_REQUEST";
export const GET_AGENT_INFO_SUCCESS = "GET_AGENT_INFO_SUCCESS";
export const GET_AGENT_INFO_FAIL = "GET_AGENT_INFO_FAIL";

export const REGISTER_PERSONAL_REQUEST = "REGISTER_PERSONAL_REQUEST";
export const REGISTER_PERSONAL_SUCCESS = "REGISTER_PERSONAL_SUCCESS";
export const REGISTER_PERSONAL_FAIL = "REGISTER_PERSONAL_FAIL";
export const UPDATE_PERSONAL_REQUEST = "UPDATE_PERSONAL_REQUEST";
export const UPDATE_PERSONAL_SUCCESS = "UPDATE_PERSONAL_SUCCESS";
export const UPDATE_PERSONAL_RESET = "UPDATE_PERSONAL_RESET";
export const UPDATE_PERSONAL_FAIL = "UPDATE_PERSONAL_FAIL";
export const LOAD_PERSONAL_REQUEST = "LOAD_PERSONAL_REQUEST";
export const LOAD_PERSONAL_SUCCESS = "LOAD_PERSONAL_SUCCESS";
export const LOAD_PERSONAL_FAIL = "LOAD_PERSONAL_FAIL";
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";
export const UPDATE_ECONOMIC_REQUEST = "UPDATE_ECONOMIC_REQUEST";
export const UPDATE_ECONOMIC_SUCCESS = "UPDATE_ECONOMIC_SUCCESS";
export const UPDATE_ECONOMIC_RESET = "UPDATE_ECONOMIC_RESET";
export const UPDATE_ECONOMIC_FAIL = "UPDATE_ECONOMIC_FAIL";
export const UPDATE_BECONOMIC_REQUEST = "UPDATE_BECONOMIC_REQUEST";
export const UPDATE_BECONOMIC_SUCCESS = "UPDATE_BECONOMIC_SUCCESS";
export const UPDATE_BECONOMIC_RESET = "UPDATE_BECONOMIC_RESET";
export const UPDATE_BECONOMIC_FAIL = "UPDATE_BECONOMIC_FAIL";

export const COMPANY_DETAILS_REQUEST = "COMPANY_DETAILS_REQUEST";
export const COMPANY_DETAILS_SUCCESS = "COMPANY_DETAILS_SUCCESS";
export const COMPANY_DETAILS_FAIL = "COMPANY_DETAILS_FAIL";

export const COMPANY_ADMIN_DETAILS_REQUEST = "COMPANY_ADMIN_DETAILS_REQUEST";
export const COMPANY_ADMIN_DETAILS_SUCCESS = "COMPANY_ADMIN_DETAILS_SUCCESS";
export const COMPANY_ADMIN_DETAILS_FAIL = "COMPANY_ADMIN_DETAILS_FAIL";

export const BANK_DETAILS_REQUEST = "BANK_DETAILS_REQUEST";
export const BANK_DETAILS_SUCCESS = "BANK_DETAILS_SUCCESS";
export const BANK_DETAILS_FAIL = "BANK_DETAILS_FAIL";

export const BRANCH_BANK_DETAILS_REQUEST = "BRANCH_BANK_DETAILS_REQUEST";
export const BRANCH_BANK_DETAILS_SUCCESS = "BRANCH_BANK_DETAILS_SUCCESS";
export const BRANCH_BANK_DETAILS_FAIL = "BRANCH_BANK_DETAILS_FAIL";

export const BRANCH_DETAILS_REQUEST = "BRANCH_DETAILS_REQUEST";
export const BRANCH_DETAILS_SUCCESS = "BRANCH_DETAILS_SUCCESS";
export const BRANCH_DETAILS_FAIL = "BRANCH_DETAILS_FAIL";

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const ALL_AGENT_REQUEST = "ALL_AGENT_REQUEST";
export const ALL_AGENT_SUCCESS = "ALL_AGENT_SUCCESS";
export const ALL_AGENT_FAIL = "ALL_AGENT_FAIL";

export const ALL_COMPANIES_REQUEST = "ALL_COMPANIES_REQUEST";
export const ALL_COMPANIES_SUCCESS = "ALL_COMPANIES_SUCCESS";
export const ALL_COMPANIES_FAIL = "ALL_COMPANIES_FAIL";

export const ALL_AGENT_USERS_REQUEST = "ALL_AGENT_USERS_REQUEST";
export const ALL_AGENT_USERS_SUCCESS = "ALL_AGENT_USERS_SUCCESS";
export const ALL_AGENT_USERS_FAIL = "ALL_AGENT_USERS_FAIL";
export const ALL_AGENT_COMPANIES_REQUEST = "ALL_AGENT_COMPANIES_REQUEST";
export const ALL_AGENT_COMPANIES_SUCCESS = "ALL_AGENT_COMPANIES_SUCCESS";
export const ALL_AGENT_COMPANIES_FAIL = "ALL_AGENT_COMPANIES_FAIL";


export const ALL_BANKS_REQUEST = "ALL_BANKS_REQUEST";
export const ALL_BANKS_SUCCESS = "ALL_BANKS_SUCCESS";
export const ALL_BANKS_FAIL = "ALL_BANKS_FAIL";

export const ALL__BANKS_REQUEST = "ALL__BANKS_REQUEST";
export const ALL__BANKS_SUCCESS = "ALL__BANKS_SUCCESS";
export const ALL__BANKS_FAIL = "ALL__BANKS_FAIL";

export const ACTIVATE_SUCCESS="ACTIVATE_SUCCESS";
export const ACTIVATE_REQUEST="ACTIVATE_REQUEST";
export const ACTIVATE_FAIL="ACTIVATE_FAIL";
export const ACTIVATE_RESET="ACTIVATE_RESET";

export const GET_BANK_BARNCH_REQUEST="GET_BANK_BRANCH_REQUEST"
export const GET_BANK_BARNCH_SUCCESS="GET_BANK_BRANCH_SUCCESS"
export const GET_BANK_BARANCH_FAIL="GET_BANK_BRANCH_FAIL"

export const GET_MYBANK_BARNCH_REQUEST="GET_MYBANK_BRANCH_REQUEST"
export const GET_MYBANK_BARNCH_SUCCESS="GET_MYBANK_BRANCH_SUCCESS"
export const GET_MYBANK_BARANCH_FAIL="GET_MYBANK_BRANCH_FAIL"

export const FORGOT_PASSWORD_REQUEST="FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL="FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_RESET="FORGOT_PASSWORD_RESET";
 
export const RECOVER_PASSWORD_REQUEST="RECOVER_PASSWORD_REQUEST";
export const RECOVER_PASSWORD_SUCCESS="RECOVER_PASSWORD_SUCCESS";
export const RECOVER_PASSWORD_FAIL="RECOVER_PASSWORD_FAIL";
export const RECOVER_PASSWORD_RESET="RECOVER_PASSWORD_RESET";

export const DEACTIVATE_ACCOUNT_REQUEST="DEACTIVATE_ACCOUNT_REQUEST";
export const DEACTIVATE_ACCOUNT_SUCCESS="DEACTIVATE_ACCOUNT_SUCCESS";
export const DEACTIVATE_ACCOUNT_FAIL="DEACTIVATE_ACCOUNT_FAIL";
export const DEACTIVATE_ACCOUNT_RESET="DEACTIVATE_ACCOUNT_RESET";

export const DEACTIVATE_MY_ACCOUNT_REQUEST="DEACTIVATE_MY_ACCOUNT_REQUEST";
export const DEACTIVATE_MY_ACCOUNT_SUCCESS="DEACTIVATE_MY_ACCOUNT_SUCCESS";
export const DEACTIVATE_MY_ACCOUNT_FAIL="DEACTIVATE_MY_ACCOUNT_FAIL";
export const DEACTIVATE_MY_ACCOUNT_RESET="DEACTIVATE_MY_ACCOUNT_RESET";

export const AGENT_DETIALS_REQUEST="AGENT_DETIALS_REQUEST";
export const AGENT_DETIALS_SUCCESS="AGENT_DETIALS_SUCCESS";
export const AGENT_DETIALS_FAIL="AGENT_DETIALS_FAIL";